default_platform(:ios)

platform :ios do
  desc "Prepare and Sync Provisioning Profiles (Certificates)"
  lane :certificates do
    # Using 'match' guarantees team-wide secure certificate syncing
    match(type: "appstore", readonly: true)
  end

  desc "Build Signed Production iOS Application"
  lane :build_ipa do
    sh("flutter build ios --release --no-codesign") # Prep build
    gym(
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "../build/ios/ipa"
    )
  end

  desc "Deliver build silently to Apple TestFlight for evaluation"
  lane :beta do
    # Uploads to App Store Connect TestFlight stream automatically!
    upload_to_testflight(
      ipa: "../build/ios/ipa/Runner.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
