; ==========================================
; Access Paralegal PDF Merger - Installer Configuration
; Generated by Antigravity AI
; ==========================================

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{86C436C7-1A84-4DCA-88EA-FF879B4B43D2}
AppName=Access Paralegal PDF Merger
AppVersion=1.2.5
AppVerName=Access Paralegal PDF Merger v1.2.5
AppPublisher=Access Paralegal Services
AppPublisherURL=https://www.accessparalegalservices.com/
AppSupportURL=https://www.accessparalegalservices.com/
AppUpdatesURL=https://github.com/woodyardae/Access_Paralegal_PDF_Merger/releases
DefaultDirName={autopf}\Access Paralegal PDF Merger
DefaultGroupName=Access Paralegal PDF Merger
AllowNoIcons=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\aewoo\Desktop\Access_PDF_Merger
OutputBaseFilename=Access_Paralegal_Setup_v1.2.5
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\aewoo\Desktop\Access_PDF_Merger\Access_Paralegal_PDF_Merger.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\aewoo\Desktop\Antigravity Workspace\adventures-of-sparky-and-claw\logo_small.png"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Access Paralegal PDF Merger"; Filename: "{app}\Access_Paralegal_PDF_Merger.exe"
Name: "{group}\{cm:UninstallProgram,Access Paralegal PDF Merger}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Access Paralegal PDF Merger"; Filename: "{app}\Access_Paralegal_PDF_Merger.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Access_Paralegal_PDF_Merger.exe"; Description: "{cm:LaunchProgram,Access Paralegal PDF Merger}"; Flags: nowait postinstall skipifsilent
