; ==========================================
; Access Paralegal Multitool - Installer Configuration
; Generated by Antigravity AI
; ==========================================

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{86C436C7-1A84-4DCA-88EA-FF879B4B43D2}
AppName=Access Paralegal Multitool
AppVersion=1.0.0
AppVerName=Access Paralegal Multitool v1.0.0
AppPublisher=Access Paralegal Services
AppPublisherURL=https://www.accessparalegalservices.com/
AppSupportURL=https://www.accessparalegalservices.com/
AppUpdatesURL=https://github.com/woodyardae/Access_Paralegal_Multitool/releases
DefaultDirName={autopf}\Access Paralegal Multitool
DefaultGroupName=Access Paralegal Multitool
AllowNoIcons=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\aewoo\Desktop\Access_APMultitool_Build
OutputBaseFilename=Access_Paralegal_Multitool_Setup_v1.0.0
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\aewoo\Desktop\Access_APMultitool_Build\Access_Paralegal_Multitool.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\aewoo\Desktop\Antigravity Workspace\adventures-of-sparky-and-claw\logo_small.png"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Access Paralegal Multitool"; Filename: "{app}\Access_Paralegal_Multitool.exe"
Name: "{group}\{cm:UninstallProgram,Access Paralegal Multitool}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Access Paralegal Multitool"; Filename: "{app}\Access_Paralegal_Multitool.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Access_Paralegal_Multitool.exe"; Description: "{cm:LaunchProgram,Access Paralegal Multitool}"; Flags: nowait postinstall skipifsilent
